### ISSUE TITLE
Update Getting Started guide

### ISSUE THREAD

**Issue by hameno** [thannaske/hetzner-cloud-ansible-inventory#2]
The [installation steps](https://github.com/thannaske/hcloud-ansible-inv/wiki/Getting-Started#installation) are outdated. Took a while for me to notice that the repository has been renamed. Should probably be updated to reflect the new name.

**Comment by thannaske** [comment]
The mentioned page should be updated now. Sorry for any inconvenience!
Furthermore I've added a 0.1-alpha release with pre-built binaries to enable other users to use the inventory script w/o setting up a whole Go build environment.

**Comment by hameno** [comment]
Are you sure the first command is correct? I'm getting the following error when running `go get -u go install github.com/thannaske/hcloud-ansible-inv`:

    package install: unrecognized import path "install" (import path does not begin with hostname)

**Comment by thannaske** [comment]
Aaaaah sorry - I just looked after the changed repository URL. That command was indeed not correct. Seems that I somehow mixed up the first and the second command. But now it should be fixed; I tested both commands and they are working as expected.
